## Equal Weights Strategy

In [27]:
import pandas as pd 
import numpy as np 
import yfinance as yf 
import math

## Load the stocks list

In [28]:
tickers = pd.read_csv('top_50_indian_stocks.csv')
tickers.head()

         Ticker               Company Name
0   RELIANCE.NS        Reliance Industries
1        TCS.NS  Tata Consultancy Services
2   HDFCBANK.NS                  HDFC Bank
3       INFY.NS                    Infosys
4  ICICIBANK.NS                 ICICI Bank

In [29]:
def fetch_market_cap(ticker_list):
    data = yf.download(ticker_list, period = '1d', group_by='ticker', auto_adjust=False)
    
    stocks_data = []
    for ticker in ticker_list:
        latest_price = data[ticker]['Close'].iloc[-1]
        market_cap = yf.Ticker(ticker).info.get("marketCap", 'N/A')
        stocks_data.append({
            "Ticker" : ticker, 
            "Market Cap" : market_cap,
            "Latest Price" : latest_price,
        })
        
    stocks_df = pd.DataFrame(stocks_data)
        
    return stocks_df
        
    

tickers_list = tickers["Ticker"].values.tolist()
df = fetch_market_cap(tickers_list)

[*********************100%***********************]  50 of 50 completed

In [30]:
df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  16447954747392   1215.449951
1          TCS.NS  14815355469824   4094.800049
2     HDFCBANK.NS  13559288299520   1772.849976
3         INFY.NS   7787016355840   1880.000000
4    ICICIBANK.NS   9047282548736   1281.650024
5   HINDUNILVR.NS   5469005414400   2326.850098
6         SBIN.NS   7094626418688    794.950012
7   BAJFINANCE.NS   4219957149696   6823.000000
8   BHARTIARTL.NS   9499619360768   1587.750000
9          ITC.NS   6051283861504    483.649994
10   KOTAKBANK.NS   3550953340928   1786.050049
11    ADANIENT.NS   2919755939840   2528.649902
12          LT.NS   4960987643904   3607.649902
13     HCLTECH.NS   5193700212736   1917.400024
14  ASIANPAINT.NS   2187134894080   2281.350098
15    AXISBANK.NS   3295352717312   1064.699951
16   SUNPHARMA.NS   4525975928832   1886.349976
17       WIPRO.NS   3156535934976    301.850006
18  ULTRACEMCO.NS   3295404883968  11426.349609
19    HDFCLIFE.NS   1328052043776    617.049988
20        ONGC.NS   3018880450560    239.250000
21        NTPC.NS   3232384942080    333.350006
22   POWERGRID.NS   2878565777408    308.700012
23  TATAMOTORS.NS   2724581081088    740.150024
24  INDUSINDBK.NS    748006801408    960.150024
25  ADANIGREEN.NS   1652184055808   1040.699951
26       TITAN.NS   2885690327040   3253.149902
27    DIVISLAB.NS   1619042238464   6098.799805
28       TECHM.NS   1514248994816   1706.199951
29      MARUTI.NS   3413913632768  10858.400391
30   COALINDIA.NS   2367412764672    384.149994
31        BPCL.NS   1268797276160    292.450012
32    JSWSTEEL.NS   2199398645760    901.500000
33     DRREDDY.NS   1157285543936   1388.500000
34  BAJAJFINSV.NS   2500319772672   1568.099976
35  ADANIPORTS.NS   2661096620032   1231.099976
36       CIPLA.NS   1234841894912   1529.000000
37   BRITANNIA.NS   1147194048512   4762.750000
38     HAVELLS.NS   1050540572672   1675.099976
39    SHREECEM.NS    930523119616  25694.199219
40      GRASIM.NS   1641694625792   2442.699951
41   TATASTEEL.NS   1721732038656    138.050003
42  HEROMOTOCO.NS    832120029184   4160.600098
43         M&M.NS   3604580925440   3007.100098
44   EICHERMOT.NS   1321837002752   4821.899902
45         IOC.NS   1926272909312    136.410004
46     SBICARD.NS    631932780544    663.849976
47  PIDILITIND.NS   1477235179520   2904.250000
48       DMART.NS   2326176727040   3561.850098
49     HDFCAMC.NS    897576271872   4199.049805

In [31]:
df = df.sort_values(by = "Market Cap", ascending=False)
df

           Ticker      Market Cap  Latest Price
0     RELIANCE.NS  16447954747392   1215.449951
1          TCS.NS  14815355469824   4094.800049
2     HDFCBANK.NS  13559288299520   1772.849976
8   BHARTIARTL.NS   9499619360768   1587.750000
4    ICICIBANK.NS   9047282548736   1281.650024
3         INFY.NS   7787016355840   1880.000000
6         SBIN.NS   7094626418688    794.950012
9          ITC.NS   6051283861504    483.649994
5   HINDUNILVR.NS   5469005414400   2326.850098
13     HCLTECH.NS   5193700212736   1917.400024
12          LT.NS   4960987643904   3607.649902
16   SUNPHARMA.NS   4525975928832   1886.349976
7   BAJFINANCE.NS   4219957149696   6823.000000
43         M&M.NS   3604580925440   3007.100098
10   KOTAKBANK.NS   3550953340928   1786.050049
29      MARUTI.NS   3413913632768  10858.400391
18  ULTRACEMCO.NS   3295404883968  11426.349609
15    AXISBANK.NS   3295352717312   1064.699951
21        NTPC.NS   3232384942080    333.350006
17       WIPRO.NS   3156535934976    301.850006
20        ONGC.NS   3018880450560    239.250000
11    ADANIENT.NS   2919755939840   2528.649902
26       TITAN.NS   2885690327040   3253.149902
22   POWERGRID.NS   2878565777408    308.700012
23  TATAMOTORS.NS   2724581081088    740.150024
35  ADANIPORTS.NS   2661096620032   1231.099976
34  BAJAJFINSV.NS   2500319772672   1568.099976
30   COALINDIA.NS   2367412764672    384.149994
48       DMART.NS   2326176727040   3561.850098
32    JSWSTEEL.NS   2199398645760    901.500000
14  ASIANPAINT.NS   2187134894080   2281.350098
45         IOC.NS   1926272909312    136.410004
41   TATASTEEL.NS   1721732038656    138.050003
25  ADANIGREEN.NS   1652184055808   1040.699951
40      GRASIM.NS   1641694625792   2442.699951
27    DIVISLAB.NS   1619042238464   6098.799805
28       TECHM.NS   1514248994816   1706.199951
47  PIDILITIND.NS   1477235179520   2904.250000
19    HDFCLIFE.NS   1328052043776    617.049988
44   EICHERMOT.NS   1321837002752   4821.899902
31        BPCL.NS   1268797276160    292.450012
36       CIPLA.NS   1234841894912   1529.000000
33     DRREDDY.NS   1157285543936   1388.500000
37   BRITANNIA.NS   1147194048512   4762.750000
38     HAVELLS.NS   1050540572672   1675.099976
39    SHREECEM.NS    930523119616  25694.199219
49     HDFCAMC.NS    897576271872   4199.049805
42  HEROMOTOCO.NS    832120029184   4160.600098
24  INDUSINDBK.NS    748006801408    960.150024
46     SBICARD.NS    631932780544    663.849976

## Taking top 10 Stocks

In [32]:
df = df.head(10)
df.reset_index(inplace=True, drop = True)
df

          Ticker      Market Cap  Latest Price
0    RELIANCE.NS  16447954747392   1215.449951
1         TCS.NS  14815355469824   4094.800049
2    HDFCBANK.NS  13559288299520   1772.849976
3  BHARTIARTL.NS   9499619360768   1587.750000
4   ICICIBANK.NS   9047282548736   1281.650024
5        INFY.NS   7787016355840   1880.000000
6        SBIN.NS   7094626418688    794.950012
7         ITC.NS   6051283861504    483.649994
8  HINDUNILVR.NS   5469005414400   2326.850098
9     HCLTECH.NS   5193700212736   1917.400024

In [33]:
portfolio_size = int(input("Enter the amount you want to invest: "))
position_size =  portfolio_size / len(df.index)
position_size

10000.0

In [34]:
df['Number of Shares to buy'] = df['Latest Price'].apply(lambda price: math.floor(
    position_size / price
))

df

/var/folders/0c/d309n6mx475_mwr1xfpx7wd80000gn/T/ipykernel_1315/3798226014.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Number of Shares to buy'] = df['Latest Price'].apply(lambda price: math.floor(

          Ticker      Market Cap  Latest Price  Number of Shares to buy
0    RELIANCE.NS  16447954747392   1215.449951                        8
1         TCS.NS  14815355469824   4094.800049                        2
2    HDFCBANK.NS  13559288299520   1772.849976                        5
3  BHARTIARTL.NS   9499619360768   1587.750000                        6
4   ICICIBANK.NS   9047282548736   1281.650024                        7
5        INFY.NS   7787016355840   1880.000000                        5
6        SBIN.NS   7094626418688    794.950012                       12
7         ITC.NS   6051283861504    483.649994                       20
8  HINDUNILVR.NS   5469005414400   2326.850098                        4
9     HCLTECH.NS   5193700212736   1917.400024                        5